"""
ChromaDB Vector Store for document embeddings.

Pipeline step: Gemini Embedding → **Chroma Vector DB** → RAG Retrieval
"""
from __future__ import annotations

import logging
from pathlib import Path
from uuid import uuid4

from app.config.settings import get_settings
from app.models.document_chunk import DocumentChunk, RetrievalResult

# Suppress ChromaDB telemetry errors (posthog version mismatch)
logging.getLogger("chromadb.telemetry.product.posthog").setLevel(logging.CRITICAL)


class VectorStore:
    """
    ChromaDB-backed vector store for document chunks.
    
    Stores embeddings generated by Gemini and enables
    similarity search for RAG retrieval.
    """

    def __init__(self) -> None:
        self._settings = get_settings()
        self._persist_dir = Path(self._settings.chroma_persist_dir)
        self._persist_dir.mkdir(parents=True, exist_ok=True)
        self._client = None

    def _get_client(self):
        """Lazy-load ChromaDB client."""
        if self._client is None:
            try:
                import chromadb
                from chromadb.config import Settings as ChromaSettings
            except ImportError:
                raise RuntimeError("chromadb required: pip install chromadb")
            
            self._client = chromadb.PersistentClient(
                path=str(self._persist_dir),
                settings=ChromaSettings(anonymized_telemetry=False),
            )
        return self._client

    def _get_collection(self, job_id: str):
        """Get or create a collection for a job."""
        client = self._get_client()
        # Collection name must be alphanumeric with underscores, max 63 chars
        name = f"job_{job_id}".replace("-", "_")[:63]
        return client.get_or_create_collection(
            name=name,
            metadata={"hnsw:space": "cosine"},
        )

    async def add_chunks_with_embeddings(
        self,
        job_id: str,
        chunks: list[DocumentChunk],
        embeddings: list[list[float]],
    ) -> int:
        """
        Store chunks with their pre-computed embeddings.
        
        Pipeline: Document → Chunk → Gemini Embedding → **Store in Chroma**
        
        Returns: number of chunks stored
        """
        if not chunks or len(chunks) != len(embeddings):
            return 0
        
        collection = self._get_collection(job_id)
        
        ids = [str(uuid4()) for _ in chunks]
        documents = [c.content for c in chunks]
        metadatas = [
            {
                "job_id": job_id,
                "chunk_index": c.chunk_index,
                "source_file": c.source_file or "",
                "token_count": c.token_count,
            }
            for c in chunks
        ]
        
        collection.add(
            ids=ids,
            embeddings=embeddings,
            documents=documents,
            metadatas=metadatas,
        )
        
        return len(chunks)

    async def search_similar(
        self,
        job_id: str,
        query_embedding: list[float],
        top_k: int = 5,
    ) -> list[RetrievalResult]:
        """
        Search for similar chunks using query embedding.
        
        Pipeline: **RAG Retrieval** (similarity search)
        
        Returns: list of RetrievalResult with chunks and scores
        """
        collection = self._get_collection(job_id)
        
        # Ensure we don't request more than available
        count = collection.count()
        if count == 0:
            return []
        
        result = collection.query(
            query_embeddings=[query_embedding],
            n_results=min(top_k, count),
            include=["documents", "metadatas", "distances"],
        )
        
        if not result["ids"] or not result["ids"][0]:
            return []
        
        retrieval_results: list[RetrievalResult] = []
        
        for i, doc_id in enumerate(result["ids"][0]):
            doc = result["documents"][0][i] if result.get("documents") else ""
            meta = result["metadatas"][0][i] if result.get("metadatas") else {}
            distance = result["distances"][0][i] if result.get("distances") else 0.0
            
            # Convert cosine distance to similarity score (1 = identical, 0 = orthogonal)
            score = 1.0 - float(distance) if distance else 1.0
            
            chunk = DocumentChunk(
                job_id=job_id,
                content=doc,
                chunk_index=meta.get("chunk_index", 0),
                token_count=meta.get("token_count", 0),
                source_file=meta.get("source_file", ""),
            )
            
            retrieval_results.append(
                RetrievalResult(chunk=chunk, score=score, metadata=meta)
            )
        
        return retrieval_results

    def get_all_chunks(self, job_id: str) -> list[DocumentChunk]:
        """Get all chunks for a job (no similarity search)."""
        collection = self._get_collection(job_id)
        count = collection.count()
        if count == 0:
            return []
        
        result = collection.get(include=["documents", "metadatas"])
        
        chunks = []
        for i, doc in enumerate(result.get("documents", [])):
            meta = result["metadatas"][i] if result.get("metadatas") else {}
            chunks.append(
                DocumentChunk(
                    job_id=job_id,
                    content=doc,
                    chunk_index=meta.get("chunk_index", 0),
                    token_count=meta.get("token_count", 0),
                    source_file=meta.get("source_file", ""),
                )
            )
        return chunks

    def delete_job(self, job_id: str) -> None:
        """Remove all vectors for a job."""
        try:
            client = self._get_client()
            name = f"job_{job_id}".replace("-", "_")[:63]
            client.delete_collection(name)
        except Exception:
            pass

    def get_chunk_count(self, job_id: str) -> int:
        """Get number of chunks stored for a job."""
        try:
            collection = self._get_collection(job_id)
            return collection.count()
        except Exception:
            return 0
